version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  robofinance:
    image: robofinance:local
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
volumes:
  database: